ZONE_3_INTEREST_HANDLE = 1
LOBBIES_INTEREST_HANDLE = 2
REQUIRED_ZONE_INTEREST_HANDLE = 3
ZONE_INTEREST_HANDLE = 4
DUNGEON_INTEREST_HANDLE = 5
DEFAULT_DUNGEON_ZONE = 6
TUTORIAL_LOBBY_INTEREST_HANDLE = DEFAULT_DUNGEON_ZONE
YARD_INTEREST_HANDLE = 69
